##
# Code Quality workflow
#
# Make sure that the PR is following
# our guide for code quality.
##

name: Code Quality

on: push

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Sync
        uses: actions/checkout@v4

      - name: Run composer
        run: composer update --prefer-dist --no-progress

      - name: Run lint
        run: composer lint

      - name: Run check
        run: composer check

      - name: Run tests
        run: composer test

